### PR TITLE
Annotations + adding "non-applicable" test type

### PR DESCRIPTION
**Pull request by frankelavsky**
Howdy @trallard, @pavithraes, @mattpap, and @gabalafou! This is a collection of tests related to annotations and the annotations API (titles, tooltip, legends, etc). I had intended to finish this be the end of Nov, but I still have a few pesky items to get to. Expect these (as a final audit PR) + some summarization (issues + discussions) from me this month.

This PR does add one additional thing, now that I've inspected the wonderful site by @pavithraes: I added a "non-applicable" folder, to help organize our tests even more. Many of the tests (especially in annotations) aren't passing and aren't failing, but simply not applicable. Some are like this in Plot Tools and a small handful are like this in Plotting Interface.

Would it be possible to add this in to the API for building the site, to make it a third category for our tests? Not entirely sure how the build works, or else I might have snuck that change in myself, too.

### CODE REVIEW

**Comment by frankelavsky** [comment]
Woah, thanks to the [despell check](https://results.pre-commit.ci/run/github/838289610/1733102991.CZnwGRh8Sl20haNZwaV4sg) I now realize that I've been spelling "forgiveable" (and it's negative "unforgiveable") incorrectly for years. Also, this is incorrect in chartability too. I'll change that down the road eventually.

**Comment by pavithraes** [comment]
Thanks! I'll open a PR against this PR branch with docs-site specific updates. :)

**Comment by frankelavsky** [comment]
Hey @pavithraes and @trallard: hold up on merging this just yet. I just realized that I have a folder of evidence I need to convert over to the new image and video syntax that I forgot to do. Expect that commit shortly and this PR to be done later today!

And as a note: one downside to the new syntax is that the markdown files are no longer usable as standalones (such as viewing on github or downloading and viewing). The images and videos in each evidence file/page are _only_ viewable on the site now. Is there a way we can easily make the markdown images (at least) still work if someone comes to github and views the files directly? It's not a big deal, of course, but it still would be nice to have.

**Comment by trallard** [comment]
Well we can instead of using a path relative to the docs content we can point to the URL of origin in the repo. That should work for both.

**Comment by frankelavsky** [comment]
I don't know if it is path-related so much as the fact that on github (and when you download and view the markdown), the images and videos render as `code` blocks with only text:
Screenshot of github's markdown viewer. No images are shown, only code blocks that contain the syntax specification for images.

Example file, viewed on github: https://github.com/Quansight-Labs/bokeh-a11y-audit/blob/main/source/plotting-interface/contrast.md

**Comment by frankelavsky** [comment]
Although, your point about using the repo URL is actually awesome and I didn't think of that. But now that we have a site up, that is definitely better.

**Comment by trallard** [comment]
Ahhhh, yes, that would be because we are using Sphinx for the site, which is quite annoying. Let me see if there is something we can do about it

**Comment by frankelavsky** [comment]
No worries if we can't do it, it's just a nice-to-have. For now though, all of the tests are up and this PR is done. Auditing's evidence collection has officially completed!  🎉 🎉

**Comment by trallard** [comment]
Yay 🎉 🚀 mega @frankelavsky 
I will go ahead and merge this PR then

**Pull request merged**
